### ISSUE TITLE
Dataset Upload With Schema

### ISSUE THREAD

**Issue by harsh-tamr** [Datatamer/tamr-client#102]
# 💬 RFC

Currently it is hard to upload a dataset with a custom schema. Given a dataset name, schema as json, and csv, efficiently upload the data. For some datasets, it's useful to generate guids for the primary key field if it doesn't exist.

## 🔦 Context

I want to upload a dataset for golden records and bootstrap it, to do this I need a dataset with strings for the origin source name field and uploading via the csv endpoint in the UI converts everything to [string]

**Comment by pcattori** [comment]
@harsh-tamr could you provide some example usage code that shows how you envision this could be done?

**Comment by nbateshaus** [comment]
Is this a dupe with #67 ?

**Comment by pcattori** [comment]
@nbateshaus #67 should be the canonical issue for discussing the design of this feature, whereas this issue should be treated as a data point / use-case for needing this feature. I'll remove the RFC tag on this issue to clarify that.

**Comment by pcattori** [comment]
Fixed by #247
