### ISSUE TITLE
Client should print helpful messages when it raises exceptions

### ISSUE THREAD

**Issue by harlankadish** [Datatamer/tamr-client#307]
# 🙋 feature request

When a colleague tried to use the Tamr client to create a project, her terminal printed a 400 error for "Bad request," and of course Python pointed to the line number in her code. As a new hire, she didn't know what could be bad about the request, especially because the Tamr client structured most of the request for her. We eventually determined that her project spec JSON had the project type as "MASTERING" when Tamr expects "DEDUP." Surely the Tamr client can be improved to parse the error messages from Tamr and pass them on to the user, perhaps as a note to stdout or as the improved text of an exception.

## 🤔 Expected Behavior

In the above example, at least the Tamr client should make available some message to at least suggest that the project spec JSON might have invalid or missing values. That's a reasonable suggestion given that the only possibility for user error in this method is the project spec. At the most, the Tamr client can check the format and values of specs and other method arguments and return helpful errors.

## 😯 Current Behavior

Now, the user needs to either include exception handling for every use Tamr client usage, or read the documentation closely to intuit the problem. Both of these options are contrary to the goal (as I understand it) of the Tamr client: to make Tamr easier to use for our customers.

## 💁 Possible Solution

See expected behavior above.

**Comment by pcattori** [comment]
Yes, we currently call [`response.raise_for_status()`](https://github.com/Datatamer/tamr-client/blob/master/tamr_unify_client/client.py#L19), but that hides the actual response body that often contains useful info from the server. We could instead [catch the `RequestException` and print out more useful info from the request/response](https://github.com/Datatamer/ml-lab/blob/master/experiment.py#L183)

**Comment by harlankadish** [comment]
Yeah, I think it'd be nice to have any approach that allows the client's users to both (1) see the error info but also (2) decide if/how to handle the exception.
