### ISSUE TITLE
Support for Backup of Tamr

### ISSUE THREAD

**Issue by licleary** [Datatamer/tamr-client#313]
# 🙋 feature request

To run a backup of Tamr and assert its success.

## 🤔 Expected Behavior
```
operation = tamr.backup.refresh()
assert operation.succeeded()
```

## 🔦 Context
We often schedule backups of Tamr deployments.

## 💻 Examples
Tamr's API v1 has the following endpoints to support backup creation.

- `GET /v1/backups` Get all backups
- `POST /v1/backups` Initiate an asynchronous backup operation
- `GET /v1/backups/{backupId}` Get a backup by ID
- `POST /v1/backups/{backupId}:cancel` Cancel a running backup, given its ID

**Comment by pcattori** [comment]
Note to future implementor: Syntactically, this should be implemented as `tamr.backup()` rather than `tamr.backup.refresh()`

**Comment by nbateshaus** [comment]
Since a Backup is a thing, and `backups` is a collection, shouldn't this support e.g.:
```
for backup in tamr.backups:
   print(backup.id)
backup = tamr.backups.create(backup_spec)
print(backup.id)
backup.cancel()
```

**Comment by pcattori** [comment]
^yes, for `tamr_unify_client`. BETA will be same conceptually by slightly different syntax

**Comment by abafzal** [comment]
if i want to add backup/restore functionality to the beta, should i create a new script called backup.py and restore.py in tamr_client?

**Comment by skalish** [comment]
My suggestion for the beta design is to either create the functions to start/cancel/get these in `instance.py`, or if needed, turn `instance` into a subpackage containing `_instance.py`, `backup.py`, and `restore.py`.  See the structure of `dataset` for example.
