### ISSUE TITLE
Support taxonomy export

### ISSUE THREAD

**Issue by abafzal** [Datatamer/tamr-client#322]

**Comment by pcattori** [comment]
@abafzal what does "export" mean precisely for taxonomies? Which API endpoints does it correspond to?

**Comment by abafzal** [comment]
`post /v1/projects/{project}/taxonomy/categories ` and  `post /v1/projects/{project}/taxonomy/categories:bulk`

**Comment by abafzal** [comment]
actually we already have this. my bad. closing this thread.
