### ISSUE TITLE
tamr.datasets.create_from_dataframe should use dtype=str to avoid dataset upload error

### ISSUE THREAD

**Issue by abafzal** [Datatamer/tamr-client#323]
# 🙋 feature request

when reading csv data type should be specified as string:

## 🤔 Expected Behavior
no error when uploading dataset because all data types will be string
## 😯 Current Behavior

otherwise you'll get errors like the following:
WARN <62288714-cef1-4078-92b6-f3879955d3b5> [2020-01-10 01:50:12,294] com.tamr.dataset.service.UpdateService: Found 1 errors when parsing/validating update commands. Check the update response for more details.
WARN <62288714-cef1-4078-92b6-f3879955d3b5> [2020-01-10 01:50:12,294] com.tamr.dataset.service.UpdateService: Sample error: Expected type '"string"' but found value '67661.0' of type 'java.lang.Double'

## 💁 Possible Solution

import pandas as pd
df = pd.read_csv("my_data.csv")
dataset = tamr.datasets.create_from_dataframe(df, "primary key name", "My Data", dtype=str)
 

## 🔦 Context

1. it made me sad
2. i had to go look at the tamr logs (this is the main cause of aforementioned sadness)

## 💻 Examples

from tamr_unify_client import Client
from tamr_unify_client.auth import UsernamePasswordAuth
import os
import pandas as pd

username = 'myusernameisawesome'
password = 'mypasswordisnotsogreat'
auth = UsernamePasswordAuth(username, password)

host = 'localhost' # replace with your Tamr host
tamr = Client(auth, host=host)

data_dir = '/path/to/data/dir'
data_files = sorted(os.listdir(data_dir))
for data_file in data_files[1:]:
    print(data_file)
    df = pd.read_csv(os.path.join(data_dir, data_file), dtype=str)
    df['primaryKey'] = df.index 
    dataset = tamr.datasets.create_from_dataframe(df, "primaryKey", data_file)

**Comment by rhulasi** [comment]
I also ran into this, and my python client returned a 400 bad request at the point of uploading the data.  Would be great to at the very least provide some feedback to the user that there's a datatype mismatch, or be more accommodating of the variety of datatypes possible in a pandas dataframe.  The expectation from the documented example is that I can take any given dataframe and use it with this function.

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py in create_from_dataframe(self, df, primary_key_name, dataset_name, ignore_nan)
    163             response = dataset.upsert_records(
--> 164                 records, primary_key_name, ignore_nan=ignore_nan
    165             )
/usr/local/lib/python3.6/site-packages/tamr_unify_client/dataset/resource.py in upsert_records(self, records, primary_key_name, **json_args)
    102         )
--> 103         return self._update_records(updates, **json_args)
    104 
/usr/local/lib/python3.6/site-packages/tamr_unify_client/dataset/resource.py in _update_records(self, updates, **json_args)
     80                 headers={"Content-Encoding": "utf-8"},
---> 81                 data=stringified_updates,
     82             )
/usr/local/lib/python3.6/site-packages/tamr_unify_client/client.py in successful(self)
     18     """
---> 19     self.raise_for_status()
     20     return self
~/Library/Python/3.6/lib/python/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
HTTPError: 400 Client Error: Bad Request for url: http://10.20.255.41:9100/api/versioned/v1/datasets/26:updateRecords
During handling of the above exception, another exception occurred:
CreationError                             Traceback (most recent call last)
<ipython-input-5-7af8cd90a05f> in <module>
      1 # Create dataset
      2 df = pd.read_csv("/Users/ravihulasi/Documents/Source_Data/test_sorting.csv")
----> 3 dataset = tamr.datasets.create_from_dataframe(df, "ID", "test_python_client_from_df")
/usr/local/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py in create_from_dataframe(self, df, primary_key_name, dataset_name, ignore_nan)
    165             )
    166         except HTTPError:
--> 167             self._handle_creation_failure(dataset, "Records could not be created")
    168 
    169         if not response["allCommandsSucceeded"]:
/usr/local/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py in _handle_creation_failure(self, dataset, error)
    185         except HTTPError:
    186             raise CreationError("Created dataset didn't delete after an earlier error")
--> 187         raise CreationError(error)
    188 
    189     # super.__repr__ is sufficient
CreationError: Records could not be created`

**Comment by nbateshaus** [comment]
just using `dtype=str` isn't right - Tamr attributes can, in fact, have different types, and it's up to the user to get the types right.
Instead, `create_from_dataframe` should interrogate the types of the columns in the dataframe and create attributes with compatible types.

**Comment by abafzal** [comment]
All data in tamr is given type array(string) at ingest time presently so I
see no issue in specifying type=str. Note that we have a separate endpoint
for ingesting geo data.
-- 
Afsana Afzal, Senior DataOps Engineer
www.tamr.com

**Comment by abafzal** [comment]
@pcattori what is the current feeling on this? can i put up a PR to force all data ingested into tamr to string?

**Comment by pcattori** [comment]
@abafzal I know we have a specific endpoint for ingesting Geo data, but if I understand correctly thats for ingesting a Geo-only data file (as opposed to a table with mostly string columns, but also including 1+ columns that are geo type).

To move forward, I think it makes sense to *assume* (read: set as a default) that all columns are type `str`, but let the user specify the types if they want to override this. So a PR that adds a `dtype` parameter (defaulted to `str`) to the `create_from_dataframe` method would be welcome

**Comment by abafzal** [comment]
i dont think the change needs to be made in `create_from_dataframe`, the data type should just be specified when the file is loaded as a dataframe using read_csv in pandas. i have updated the documentation to add this. `create_from_dataframe` takes in a dataFrame object so the dataframe should come in properly typed. Lmk if that makes sense.

**Comment by pcattori** [comment]
Yes, if we depend on the user setting up `dtype`s correctly via docs, this will address the issue.

The alternative I proposed was that we would assume `dtype=str` for any dataframes passed into `create_from_dataframe` *even if the user hasn't set dtype* (with the option to override this of course).

I think your solution of just relying on docs for now makes sense. @skalish is already working on related features which are making us think about how to handle this better in code. But yes, agreed, docs for now 😄

**Comment by pcattori** [comment]
Closing since users should have control over `dtypes` and docs are now updated to provide guidance on this.

Feel free to reopen if we missed something.
