### ISSUE TITLE
Can't run EstimatePairs from tamr_client if estimate never previously run

### ISSUE THREAD

**Issue by keziah-tamr** [Datatamer/tamr-client#342]
# 🐛 bug report

Cannot submit an Estimate Pairs job using the tamr-client if Estimate Pairs has never been run before for that project

## 🤔 Expected Behavior
target_project = client.projects.by_resource_id('7').as_mastering()
target_project.estimate_pairs().refresh()
// an estimate pairs job is started

## 😯 Current Behavior

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://10.20.0.15:9100/api/versioned/v1/projects/7/estimatedPairCounts

This occurs only if estimate pairs has never been called previously for a project. In this example, every other job had been previously run for the project (clusters have been published)

Traceback (most recent call last):
  File "/Users/keziah/Documents/github/personal/keziah.katz/scratch/now.py", line 275, in <module>
    target_project.estimate_pairs().refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tamr_unify_client/mastering/project.py", line 188, in estimate_pairs
    estimate_json = self.client.get(alias).successful().json()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tamr_unify_client/client.py", line 33, in successful
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tamr_unify_client/client.py", line 27, in successful
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://10.20.0.15:9100/api/versioned/v1/projects/7/estimatedPairCounts

## 💁 Possible Solution

Return an empty EstimatedPairCounts object if the job has never been run before

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| tamr-unify-client | 0.10.0
| Tamr server       | v2020.001.0
| Python            |
| Operating System  |

**Comment by pcattori** [comment]
@keziah-tamr If you do this directly via APIs, do you get the same error? If so, is there a way to do this via APIs that doesn't give you this error?

**Comment by keziah-tamr** [comment]
@pcattori Yes it can be done as expected through the versioned APIs. For a project that has never had estimate counts run: 

- Using `GET /v1/projects/{project}/estimatedPairCounts` fails (which I would expect). It returns a 404 with the message "No estimated pair counts calculated for project 7".
- Using `POST /v1/projects/{project}/estimatedPairCounts:refresh` (which is what I was trying to do using the client) successfully submits a job.

I believe it is similar to how with the client we need to run "d.create_profile()" for the first run and then can use "d.profile().refresh()" for subsequent runs

**Comment by pcattori** [comment]
Ah ok so the design issue here is the assumption that a resource exists if we are accessing a URL that branches from that resource's URL. This might be a place where the design of the client/SDK *should* abstract away these API details so that we don't run into these sorts of issues.

**Comment by skalish** [comment]
For both operations, profiling a dataset and estimating pair counts for a project, does it make sense that if the initial estimation/profiling has not been done, that the calls `d.profile().refresh()` / `p.estimate_pairs().refresh()` should raise exceptions or instead attempt creation of the missing object? 

Is the better solution (from a usability and design perspective) to:
- A) Raise an exception and direct the user to run `d.create_profile()` / `p.create_pair_estimate()`
- B) Handle this automatically in the code, so to a user the first profile/estimate is made the same way as any subsequent update

?

**Comment by pcattori** [comment]
We are stuck between two competing mental models:

1. UI is push-centric. I have the inputs and the operation, so I run it to produce an output.
2. API is pull-centric. I have a resource so I call refresh and the system figures out what's needed and does it.

If we embrace (1), then option (A: raise an exception directing the user) seems more inline.
If we go with (2), then option(B: handle this automatically) seems better.

**Comment by skalish** [comment]
This issue is avoided in the TC implementation introduced by #440. The function `tc.mastering.estimate_pairs` calls `POST /v1/projects/{project}/estimatedPairCounts:refresh` and in no way requires a successful call of `GET /v1/projects/{project}/estimatedPairCounts`.

**Comment by pcattori** [comment]
Resolved by #440

**Comment by keziah-tamr** [comment]
This is still a bug in tamr_unify_client though. Shouldn't it be left open as a known bug or something?
