### ISSUE TITLE
Composite key support

### ISSUE THREAD

**Issue by pcattori** [Datatamer/tamr-client#349]
# 💬 RFC

Parts of the Tamr API support composite keys (CK) for datasets (e.g. multiple attributes constituting a primary key), but its not clear if `tamr-client` should support CK.

## 🔦 Context

Questions:
1. Do *all* parts of the versioned API support CK?
2. Does the Tamr backend support CK?
3. Does the Tamr UI support CK?
4. Is "composite keys" the correct term? API also refers to this concept as `key_attribute_names`.

Specifically, #348 needs answers in order to design the interface for record creation/updates, among other things.

## 💻 Examples

Currently, users must specify a `primary_key_name` for record upserts:

```python
tc.record.upsert(s, dataset, records, primary_key_name="my id")
```

In this case, we maybe should just grab the primary key/composite key from the `dataset`, not as for it from the user.

Even if we don't need to ask for PK/CK for upserts, we will need to ask for PK/CK for dataset creation (note: this functionality does not exist yet):

```python
dataset = tc.dataframe.create(s, df, primary_key_name="my id")
```

**Comment by samgqroberts** [comment]
For what it's worth, my take on this is that CK support has been in Tamr at a low-level for a while now (certain internal workflows create and use Datasets with CKs), but to my knowledge that capability has never been surfaced in any particular end-user feature. It may be possible, depending on the charter of the versioned API / python client, to surface that low-level support directly in Dataset uploads.

**Comment by pcattori** [comment]
Proposal:

For now, accept `primary_key_name : str` as a keyword-only arg.
We can then incrementally add `composite_key_names: List[str]` as a keyword-only arg to add support for composite keys in a backwards-compatible way.

@nbateshaus @skalish : thoughts?

**Comment by skalish** [comment]
That seems reasonable to me, however, it isn't much work to include that now.  If my understanding is correct, the main change will be in the formatting of the CREATE/DELETE commands.

**Comment by pcattori** [comment]
@skalish : I'd say we hold off on implementing composite key support until we have the designs finalized for some usable piece of the backend. Could be that those designs influence the design we want to take here.

Right now we just have to make sure we don't paint ourselves into a corner, so as long as we model things as keyword-only args, we should be fine.

**Comment by pcattori** [comment]
Closing this for now. We can reopen if/when composite keys become a user-facing feature in Tamr.
