### ISSUE TITLE
Can we get a by_name() method for projects?

### ISSUE THREAD

**Issue by lsbilbro** [Datatamer/tamr-client#35]
It's a nice feature on datasets.

**Comment by pcattori** [comment]
@lsbilbro #34 adds the ability to lookup projects by external ID. We are trying to get standardized about using external IDs for lookups and relying less on names.

That said, is there a particular use-case you have in mind where `by_name` would be more appropriate than `by_external_id`?

**Comment by lsbilbro** [comment]
hmm, no I think `by_external_id` would work for my purposes.
thanks for the update!

**Comment by nbateshaus** [comment]
By default, projects' `externalId` is a UUID, which is opaque from a scripting perspective.
When users create projects, they communicate to me the name of the project, not the external ID, so I want to be able to find the project by name.
So, yes, I still want `by_name` on ProjectCollection, which should behave like other `by_name` methods and raise `KeyError` / `LookupError` if it finds 0 / more than one matching project.

**Comment by pcattori** [comment]
AFAIK, the entire point of the `externalId` is for scripting against rename-able resources in the Unify API and we explicitly did not want a `projects.by_name` that could steer users in the wrong direction (@licleary I think this conversation was with you). Specifically, if you want to run a script against your dev environment and then run it against your prod environment, referencing with external IDs would be the way to go.

@Andy-L correct me if I'm wrong about the design of the external IDs.
 
@nbateshaus : I think the appropriate solution is to make it easier to find/hand-off external IDs. If you disagree, could you elaborate on your use-case?

**Comment by licleary** [comment]
Correct @pcattori. Clients of Unify should always refer to projects by their `externalId` property. External ID values can of course be any _unique_ string, e.g. a meaningful project name, which can be updated by an Admin user at any time. Have a look at https://docs.tamr.com/docs/creating-a-project.

We'll improve the experience around finding and updating external IDs on projects to make this clearer and easier.

**Comment by clint-richardson** [comment]
RE-opening after conversation with @pcattori, @nbateshaus , @Andy-L , and @along528 . The point is that users start with the UI, not the API, so names are the meaningful ID for them

**Comment by pcattori** [comment]
The agreement was to:

1. Provide a `by_name` function for looking up a project for basic (or UI-first) use-cases
2. Write documentation for how to use `external_id` for advanced (or API-first) use-cases
