### ISSUE TITLE
Handle pandas as an extra dependency

### ISSUE THREAD

**Issue by skalish** [Datatamer/tamr-client#351]
# 🙋 feature request
There are some external packages that are required for convenience features desired in the Tamr client, e.g. `pandas` for DataFrame support, that are difficult or impossible to have installed in some environments.  These dependencies can be changed from required or dev-dependencies into optional extras: https://python-poetry.org/docs/pyproject/#extras

Related to #324, #348 

## 💁 Possible Solution
Move `pandas` from `[tool.poetry.dev-dependencies]` to `[tool.poetry.extras]` in `pyproject.toml`.  In the related code that imports `pandas` this import could be wrapped in a `try`-`except` statement that raises a to-be-defined exception if the extra dependency has not been installed.

## 💻 Examples
```bash
poetry install --extras "pandas"
```

**Comment by pcattori** [comment]
@skalish note that the extras name should semantically be a *feature* name, not a dependency name. So "dataframe" (after the module name) might be more apt than "pandas"

**Comment by pcattori** [comment]
Resolved by #398
