### ISSUE TITLE
Add more detail to custom endpoint documentation

### ISSUE THREAD

**Issue by sabrinabarrett** [Datatamer/tamr-client#353]
# 🙋 feature request

The custom endpoint documentation points to requests.request however doesn't give an example of how to successfully call a custom tamr endpoint (e.g. including headers and using json.dumps)

## 🤔 Expected Behavior
Include an example similar to the below, for a post request:

response = tamr.post('relative/path/to/resource', headers={'Content-Type': 'application/json', 'Accept': 'application/json'}, data=json.dumps(body_json))

## 😯 Current Behavior

Currently there are no examples of a post request and therefore nothing which specifies headers/data structures.

**Comment by pcattori** [comment]
@sabrinabarrett thanks for filing this issue!

Pro tip: if you have Python `dict`s or `list`s that you need to send as JSON you can just:

```python
response = tamr.post('relative/path/to/resource', headers={'Content-Type': 'application/json', 'Accept': 'application/json'}, json=body_json)
```

Instead of manually serializing via `data=json.dumps(...)`

**Comment by sabrinabarrett** [comment]
Thanks for the tip @pcattori!

**Comment by Joe-Sin7h** [comment]
I would like to workon this issue. Can i get assigned ? @pcattori

**Comment by courtneypk-work** [comment]
@pcattori and @skalish this came up in a Customer Support request for Janssen earlier today (https://tamr.zendesk.com/agent/tickets/1236444 if you are interested in knowing more) for someone attempting to use tamr.post(). The addition of examples for `get`, `post`, `put`, & `request` would be useful to enable users who can write python but are not familiar enough with APIs to fill in the blanks.

**Comment by courtneypk-work** [comment]
This is the response provided to the Janssen user that was helpful to address his question, "When calling a POST API that expects a JSON string, how is the JSON passed to the API in the call?", which is a sensible question for one still new to APIs. 
```
body = {"name": "New Attribute 1", "description": "my attribute description", "type": {"baseType": "ARRAY", "innerType": {"baseType": "STRING"}}}
url = 'http://awsbgcnval0002.jnj.com:9100/api/versioned/v1/projects/16/attributes'
response = tamr.post(url, json=body)
print(json.dumps(response.json(), indent=2))
```
One option is to provide a general example of how to use JSON in the different request types. This is important since the underlying code uses JSON and if one looks at the documentation about using the requests library one could think that using a `dictionary` is appropriate.

**Comment by skalish** [comment]
@courtneypk-work Do you think the addition of the small section below (to the Advanced Usage page of the docs) would suffice?
![Screen Shot 2021-04-12 at 11 17 40 AM](https://user-images.githubusercontent.com/39866163/114418634-b33a6580-9b80-11eb-88f1-fd318d31b6c2.png)

**Comment by courtneypk-work** [comment]
@skalish I think that would be great. @sabrinabarrett - is this a reasonable addition in your case?

**Comment by sabrinabarrett** [comment]
Yeah I think that would be good!
