### ISSUE TITLE
Connecting to Tamr instance with implicit port raises HTTP ConnectionError

### ISSUE THREAD

**Issue by skalish** [Datatamer/tamr-client#366]
# 🐛 bug report

If a Tamr instance is located at an address that does not take the form of `http[s]://<url OR external IP>:<port>/` but instead is accessed at `http[s]://<url OR external IP>/` then `tuc` does not provide a way to create a working `Client` instance.

This seems to occur because `tuc.Client` method `origin` includes a hard-coded `:` preceding port, even if `port` is passed a value of `None` or an empty string.

## 🤔 Expected Behavior

If a user knows the address of the Tamr instance, it should be simple and intuitive to pass `port=None` or `port=""` (empty string) and have the generated path work.

## 😯 Current Behavior

HTTP ConnectionError is raised because of a malformed request.

```
ConnectionError: HTTPSConnectionPool(host='35.196.158.123', port=9100): Max retries exceeded with url: /api/versioned/v1/datasets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000248DB0A37C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```

## 💁 Possible Solution

The default value of `port` in `tuc.Client` is `9100`.  If "no port" is explicitly passed, either with `port=None` or `port=""`, then the return value of `tuc.Client.origin` should be changed, maybe in the following way:
```python
# CURRENT
return f"{self.protocol}://{self.host}:{self.port}" 

# NEW
if self.port is None or self.port == "":
    return f"{self.protocol}://{self.host}"
else:
    return f"{self.protocol}://{self.host}:{self.port}" 
```

## 🔦 Context

I was working with a partner from LMI on the NavAir project last week, and he ran into an issue using tamr-unify-client . He was not on our VPN, but had his IP whitelisted, so he had access to the Tamr instance via a URL or external IP address like so: `https://<url OR external IP>/#` (and can make API calls using curl).  Using either of these as host in tuc.Client() raised an HTTP error. 

## 💻 Code Sample

```python
import tamr_unify_client as tuc
auth = tuc.UsernamePasswordAuth("my username", "my password")

client_port_9100 = tuc.Client(auth, protocol="https", host="123.123.123.123", port="9100")
datasets = client_port_9100.datasets.stream()  # Raises ConnectionError

client_no_port = tuc.Client(auth, protocol="https", host="123.123.123.123", port="")
datasets = client_no_port.datasets.stream()  # Raises ConnectionError
```

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| tamr-unify-client | ? |
| Tamr server       | ? |
| Python            | ? |
| Operating System  | ? |

**Comment by pcattori** [comment]
The only design question I have: Should `9100` be the default port? or should `80` be the default?

**Comment by skalish** [comment]
In my experience, `9100` is typical, and I've never run into a case where I wanted to use `80`.
A design question from me would be, what should trigger no port value?  `port=None` and `port=""` both seem sort of reasonable.

**Comment by pcattori** [comment]
The type of `port` is `int`, not `str`. In any case, its better to use `Optional[int]` with `None` as a sentinel value for "no port" than to encode "no port" as `-1` or something like that.

Rephrasing my original question: should `port=None` be the default?

For users who see `https://myhost.com`, should they be expected to remember to set `port=None` when `port` isn't even a concept they may be aware of?

It seems like having users who see `https://myhost:myport.com` set `port=myport` is more reasonable.

The only complication here is that the `port=9100` use-case is extremely common.

I think I lean towards defaulting to `port=9100` with some docs that detail how to set `port=None` for URLs that lack a port.

**Comment by skalish** [comment]
I think the amount of disruption that would occur from an update that changed the default port from `9100` prohibits a change to the (much nicer) default of no port.

**Comment by skalish** [comment]
I'm going to get started on a PR for this.  Does it make sense to make this change in `tc` and `tuc` simultaneously?

**Comment by pcattori** [comment]
> I think the amount of disruption that would occur from an update that changed the default port from `9100` prohibits a change to the (much nicer) default of no port.

Not for `tamr_client` BETA, we can still change this if we think `port=None` is a better default (but like I said, I think this is debatable).

But yes, we should decide how to deal with this in TUC and TC and deal with both simultaneously.

**Comment by skalish** [comment]
On that note, I lean toward the TUC solution leaving `9100` as the default, and the TC solution using `None` as the default.

**Comment by skalish** [comment]
@pcattori It turns out that the typical Tamr deployment port depends on the protocol.  Specifically, for `http` the default port is `9100`, while for `https` the default port is `None`.  We could follow this pattern in the implementation, but I wonder if this makes for an overly complex behavior.
