### ISSUE TITLE
Doc for reading Tamr dataset records into Pandas dataframe

### ISSUE THREAD

**Issue by olivito** [Datatamer/tamr-client#376]
# 🙋 feature request

Reading the records from a Tamr dataset into a Pandas dataframe is a common use case that should be covered in the docs in a prominent place, like the `Quickstart` page.

## 💁 Possible Solution

For the simplest case, without geospatial data:

```
import pandas as pd
df = pd.DataFrame(dataset.records())
```

## 💻 Examples

@tiems90 has examples for geospatial data

**Comment by pcattori** [comment]
Resolved by #378
