### ISSUE TITLE
AttributeMappingCollection is not iterable

### ISSUE THREAD

**Issue by clint-richardson** [Datatamer/tamr-client#379]
# 🐛 bug report

Trying to iterate over an attribute mapping collection gives an error

## 🤔 Expected Behavior

I should get an iterator for the collection and be able to iterate over it

## 😯 Current Behavior

``` 
for m in mappings:
TypeError: 'AttributeMappingCollection' object is not iterable
```

## 💁 Possible Solution

workaround is to iterate over the stream so `for m in mappings.stream()`

## 🔦 Context

get mappings and see what they are

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| tamr-unify-client | 0.11.1
| Tamr server       |
| Python            |
| Operating System  |

**Comment by pcattori** [comment]
This has been addressed for TC in [release v1.3.0](https://github.com/Datatamer/tamr-client/releases/tag/v1.3.0).

Won't fix for TUC.
