### ISSUE TITLE
Create Operation from Job resource id

### ISSUE THREAD

**Issue by Lordluen** [Datatamer/tamr-client#383]
# 🙋 feature request

There are lots of jobs that can be kicked off via custom API requests. The response to those APIs usually includes the job id for the operation that has been kicked off, but the response is a 200 code (rather than 204). As a result, the current Operation.from_request() method cannot take that output to create an Operation object.

I would like a way to take a job resource id, to retrieve a job from Tamr and store it as an Operation object so that I can make use of all the nice methods within the Operation object.

## 🤔 Expected Behavior

I'm expecting something like this:
```
res = client.post("../../recipe/modules/{}/job/updateSourceList".format(module_id))
job_id = res.json()["documentId"]["id"]
op = Operation.from_resource_id(client, job_id)
assert op.succeeded()
```

## 😯 Current Behavior
Currently, I would have to submit the job via `client.post()`, and then create my own job poller, which is doable, but annoying.

## 💁 Possible Solution

With the job id, it should be possible to get the same job info that we currently get when we receive a 204 response from other requests. So then it should follow that we could generate an operation in the same way that the `from_response` method works with just a little extra work, possibly hitting the dataset API to retrieve the job info.

## 🔦 Context

I was creating a workflow using the GR module, and realized there was no easy way to kick off a job via non-versioned apis and then use the Operation object gracefully. While versioned APIs for GRs (and modules more broadly) will come out eventually and then added explicitly into this library, I suspect there will always be edge cases where a job needs to be kicked off via internal apis for cutting edge features. So I figured it would be best to have this workaround functional to support those cases.

## 💻 Examples

I have no additional examples to provide other than the one in the expected behavior section above.

**Comment by keziah-tamr** [comment]
Operation from resource_id is still missing, but there is operation.from_response, which would work for your example:
```
response_materialize = tamr_client.post(f'/api/dataset/datasets/{dataset_name}/materialize')
op = Operation.from_response(tamr_client, response_materialize)
```

You could also use it with the GET /v1/operations/{id} endpoint to get the Operation from a job id
