### ISSUE TITLE
Update the styling for Python client docs: fonts, favicon, Tamr logo, footer to match company's look and feel

### ISSUE THREAD

**Issue by JuliaMalkin** [Datatamer/tamr-client#394]
Issue:
I noticed that the text in the Tamr Python Client docs is sans serif (which is OK), but titles are in a somewhat dated-looking serif font. Tamr has a book for its logos and fonts. Please update the stylesheet for the documentation to match the Tamr company's identity and start looking attractive and modern, like it should!

AC:
1. Change font to the following widely available font: Lexen Deca: https://fonts.google.com/specimen/Lexend+Deca. 

NOTES: This has been identified by sales and marketing as the closest font to the private font used by our website. The current Titles font is Roboto-Slab, in the Georgia font family. What Font extension in Chrome tells me that the current font is serif but it doesn't look like serif to me. 

Alternatively, ask Julia where to find an internal link to dowload the Montserrat fonts that Tamr uses everywhere else. 

2.  Change the copyright year to be 2020 in the footer. 
3. Update the footer to include links to Tamr Legal Notices and Terms and Conditions. This is a standard practice. Here is an example of what we have in the Tamr docs. Maybe we can use the same:

<div class="container" >
 
<p margin-bottom: 180px>&copy; 2020,
  <a href="https://www.tamr.com/" style="color:#0859C6">Tamr, Inc.</a> 
 All rights reserved. 
 <a href="https://www.tamr.com/terms-conditions/" style="color:#0859C6">Terms of Use </a>&#124;
  <a href="https://www.tamr.com/privacy-2/" style="color:#0859C6"> Privacy Policy </a>
  </p>
</div>

4. Does readthedocs allow removing references in the footer to it and to Sphynx? If so, comment them out.

5. Update the color blue to match the Tamr blue HEX codes. 
Currently, the upper left corner has the blue that does not look like Tamr blue.
Here are the codes:
Brilliant Blue HEX 0859C6
Sky Blue  HEX 089FFF
Bright Blue HEX 00CCFF

6. Update the favicon that should show up in the browser inside the browser tab with the blue Tamr logo. See the Tamr Brand book (ask Julia for location), for the quality favicon image to download. Right now, the generic two-pane readthedocs favicon shows up. It is black and white and has no relation to Tamr which is confusing.

6. Add metadata to the headers for topmost pages to increase SEO. Consult with Trey S. from marketing which keywords to add.

**Comment by pcattori** [comment]
@JuliaMalkin requesting clarification: should Lexend Deca be used only for headers/titles, but not for body text? If so, what font should be used for body text? Montserrat or closest widely available lookalike?

**Comment by pcattori** [comment]
Before:

![Screen Shot 2020-06-26 at 6 38 12 PM](https://user-images.githubusercontent.com/1477317/85906418-3b12d700-b7dc-11ea-9a82-778e087328eb.png)


After:

![Screen Shot 2020-06-26 at 6 38 00 PM](https://user-images.githubusercontent.com/1477317/85906423-3fd78b00-b7dc-11ea-9e3b-728da2cd81d2.png)

**Comment by pcattori** [comment]
For (2), the copyright is already 2020 on latest. We just need to publish the next release for that change to be present on stable.

**Comment by JuliaMalkin** [comment]
Hi Pedro,
Thank you for making these changes.
1. RE: Lexen Deca or Montserrat, if Lexen Deca looks good, let's keep it. 
2. I think you may want to use Sky Blue HEX 089FFF instead of Brilliant Blue, because that's the color most used on the website, but please see what makes sense. Both are Tamr colors. 

I couldn't test the footer, or the favicon in the screenshot, but assume those would work. Thank you for making the changes.

**Comment by pcattori** [comment]
Resolved by #395
