### ISSUE TITLE
Design for Transformations

### ISSUE THREAD

**Issue by keziah-tamr** [Datatamer/tamr-client#417]
# 💬 RFC

Now that we have versioned APIs for transformations, we can add them to tamr-client. This is useful for things like project migration and version control of transformations.

Proposal:
- add data class for the transformations of a project
- add get and replace transformations function to the project module

## 🔦 Context

The APIs GET /v1/projects/{project}/transformations and PUT /v1/projects/{project}/transformations use json in the following format:
```
{
  "parameterized": [
    {
      "datasets": [],
      "transformation": "//all datasets\nSELECT *, 1 as one;"
    },
    {
      "datasets": [
        {
          "name": "people_tiny.csv",
          "datasetId": "unify://unified-data/v1/datasets/18",
          "relativeDatasetId": "datasets/18"
        }
      ],
      "transformation": "//just people\nSELECT *, 1 as one;"
    }
  ],
  "unified": [
    "//unified 1\nSELECT *, 1 as one;",
    "//unifed 2\nSELECT *, 1 as one;"
  ]
}
```

## 💻 Examples

Dataclass Option 1)
```
class Transformations:
    input_scope: input_scope: Optional[List[Tuple[List[Dataset], str]]] = None
    unified_scope: Optional[List[str]] = None
```

Dataclass Option 2)
```
class InputTransformation:
    script: str
    datasets: Optional[List[Dataset]] = None
    
class Transformations:
    input_scope: Optional[List[InputTransformation]] = None
    unified_scope: Optional[List[str]] = None
```    

Functions:

```
def transformations(project: Project) -> Transformations
""" Retrieves all transformations for a project"""
```
```
def replace_transformations(project: Project, transformations: Transformations) -> requests.Response
""" Replaces the current transformations of a project with a new group"""
```

**Comment by skalish** [comment]
Does it make sense for these new functions to live in the `project.py` module, so that they are called as `tc.project.transformations(s, instance, project)`?  I think this makes sense, but it is certainly not the only way to do it.

**Comment by pcattori** [comment]
Yes, as long as the API works across project types (mastering, categorization, schema mapping, etc..). I do wonder what the implications of `tc.project.transformations` would be for a Golden Records project though...

Also note: the signature would be `tc.project.transformations(s, project)` (not including `instance` because the instance is encoded in the project URL)

**Comment by pcattori** [comment]
Thought about this more. We all agree that the functions that interact with transformations should take projects (not unified datasets or other types) as input.

But I did notice that the functions are currently called `transformations` and `replace_transformations`, which immediately looks to me like an opportunity for better namespacing. E.g. a `transformations.py` module with `get_all` and `replace_all` methods or something.

The question becomes: where to put this module? Should it be `tc.transformations.get_all(s, proj)`? or `tc.project.transformations.get_all(s, proj)`? This is similar to how we deal with attributes, but the difference is that each attribute is a full-blown resource, whereas transformations are not.

**Comment by pcattori** [comment]
Another thought: Including `project` in the namespace path to `transformations` (e.g. `tc.project.transformations`) is only useful (from a namespacing perspective) if there are other valid contexts for `transformations`. If we *always* talk about getting and replacing transformations in the context of a project, then I think `tc.transformations.get_all(s, proj)` is better than `tc.project.transformations.get_all(s, proj)`. This is similar to our treatment of unified datasets where we have `tc.dataset.unified`, not `tc.project.unified`.
