### ISSUE TITLE
Testing for create projects in Tamr

### ISSUE THREAD

**Issue by abafzal** [Datatamer/tamr-client#437]
# 💬 RFC

From https://github.com/Datatamer/tamr-client/pull/435#pullrequestreview-467925578 : 
```This looks very nice. The framework for using fake.json to check if requests like these are being submitted correctly will hopefully be in soon (#432), but these also seem like the perfect options to be involved in tests against a live Tamr instance. I think it is worth merging this without that in place, but let's call out testing project creation in this way in an issue or RFC if this is merged before that.```
Testing for functions that create projects in Tamr. 

## 🔦 Context

We need testing to make sure that the requests we're sending are valid and actually do end up creating projects in Tamr as expected.

**Comment by skalish** [comment]
Relates to #423 and #432

**Comment by pcattori** [comment]
I see tests for project creation for both [Mastering](https://github.com/Datatamer/tamr-client/blob/master/tests/tamr_client/mastering/test_mastering_project.py#L6) and [Categorization](https://github.com/Datatamer/tamr-client/blob/master/tests/tamr_client/categorization/test_categorization_project.py#L6), so I think this has been addressed.

Feel free to reopen if there is an issue with tests for project creation at large, and to make separate issues for testing for other project types if desired.
