### ISSUE TITLE
Should TC functions ever have both an instance-specific object (project, dataset, ...) and an instance as arguments?

### ISSUE THREAD

**Issue by skalish** [Datatamer/tamr-client#439]
# 💬 RFC

In `tamr_client`, `Project` and `Dataset` objects are tied to a specific `Instance`.  Should any function that takes one of these as an argument also require that an `Instance` be passed?  It seems redundant to me.  There are of course plausible exceptions (such as project migration) where this is necessary.  Maybe there is a good reason to do this, maybe there is a good reason not to.

## 💻 Examples

The current implementations of the functions `tc.unified.from_project` and `tc.categorization.project.manual_labels` take both `Project` and `Instance` objects as parameters, and could be modified to require that only the `Project` is passed and use its `Instance`.
```python
def from_project(
    session: Session, instance: Instance, project: Project
) -> UnifiedDataset: ...
```
```python
def manual_labels(
    session: Session, instance: Instance, project: CategorizationProject
) -> Dataset: ...
```

**Comment by pcattori** [comment]
Agreed. Each resource has a URL which uniquely identifies it *and* its instance. Instance should be removed as an argument to these functions.

**Comment by skalish** [comment]
Partially fixed (`tc.unified.from_project`) by #442

**Comment by pcattori** [comment]
Closing this RFC as we have reached a decision: "No".
