### ISSUE TITLE
TC: Document common workflows that show function usage

### ISSUE THREAD

**Issue by abafzal** [Datatamer/tamr-client#444]
We need to write public documentation for several workflows that show users how to use functions in the Tamr Client. 

Some ideas for workflows: 

- Continuous mastering
- Continuous categorization
- Continuous schema mapping 
- Continuous golden records

- Create mastering project
- Create categorization project
- Create schema mapping project
- Create golden record project (requires existing mastering project)

Thoughts are welcome.

**Comment by pcattori** [comment]
Superseded by #449 . We can add additional workflows after continuous mastering is in.
