### ISSUE TITLE
How-to: Use `tamr_client` and `tamr-toolbox`

### ISSUE THREAD

**Issue by pcattori** [Datatamer/tamr-client#451]
# 🙋 feature request

Enable users to write scripts using `tamr_client`, but still use `tamr-toolbox` for functionality missing from TC.

## 💁 Possible Solution

Use the Tamr server as a bridge; to convert between TC and TUC, send GET requests by resource ID to convert.

## 💻 Examples

```python
# TC land
proj = tc.project.create(...)
...

# convert TC to TUC
tuc_proj = client.projects.by_resource_id(proj.resource_id)

# TUC land
tuc_dataset = toolbox.do_stuff(tuc_proj)

# convert back to TC
dataset = tc.dataset.by_resource_id(tuc_dataset.resource_id)
```

**Comment by skalish** [comment]
May or may not be useful/relevant, but here is a bit of code showing how to move between a TUC `Client` and a TC `Session`/`Instance` pair:
```python
import tamr_client as tc
from tamr_unify_client.auth import UsernamePasswordAuth
from tamr_unify_client.client import Client

# TUC client
client = Client(UsernamePasswordAuth("admin", "dt"), protocol="http", host="localhost", port=9100)

# TC session and instance
session = tc.session.from_auth(tc.UsernamePasswordAuth("username", "password"))
instance = tc.Instance(protocol="http", host="localhost", port=9100)

# TUC -> TC (Session and Instance from Client)
session_2 = tc.session.from_auth(client.auth)
instance_2 = tc.Instance(protocol=client.protocol, host=client.host, port=client.port)

# TC -> TUC (Client from Session and Instance)
client_2 = Client(session.auth, protocol=instance.protocol, host=instance.host, port=instance.port)
```

**Comment by pcattori** [comment]
Thinking about this more... given that `tamr-toolbox` is internal to Tamr and not customer-facing, do we want to reference it in our public `tamr_client` docs?

Maybe this would be best as a blog post or something. What do you guys think @skalish @clint-richardson ?

**Comment by skalish** [comment]
I think an internal blog post would be more appropriate.  Eventually, say if/when `tamr-toolbox` is made public, we can use that blog post as a starting point for docs.  It is possible that by the time of such a transition, this will no longer be an issue.

**Comment by pcattori** [comment]
Covered in this [internal blog post](https://datatamr.atlassian.net/wiki/spaces/IEB/pages/1638203875/Tamr+Client+is+approaching+v1.0)
