### ISSUE TITLE
Create a branch of python-starter-kit that uses tamr-client

### ISSUE THREAD

**Issue by skalish** [Datatamer/tamr-client#460]
# 🙋 feature request

`python-starter-kit` is the recommended starting point for a project repository that utilizes Tamr.  The current state of it uses `tamr_unify_client` via `tamr-toolbox`.  As an illustration of the recommended usage of the new `tamr_client`, and as a resource for starting new projects with it, a branch of `python-starter` kit should be created that uses `tamr_client`.

## 💁 Possible Solution

A starter repo for beginning projects that use `tamr_client` instead of `tamr_unify_client`

**Comment by skalish** [comment]
The best solution to this is the addition of a script analogous to the existing `example_script.py` in the `python-starter-kit` repo, that uses `tamr_client` instead of `tamr-toolbox` implementation of `tamr_unify_client` features.  This is pretty straightforward, but is blocked by two factors:
1. The project workflow functions are only in the development branch of `tamr-client` so installing a version of the package with them included is complicated until the next release.
2. Even in the development branch there are no `tamr_client` workflow functions for Golden Records projects, while the `tamr_toolbox` function in `example_script.py` handles any project type.  We can either add these to `tamr_client` before the next release, or punt by explicitly not allowing the new version of the script to process GR projects.
@pedro any thoughts on these two points?

**Comment by pcattori** [comment]
Relates to Datatamer/python-starter-kit#37
