### ISSUE TITLE
Change name of default branch from `master` to `main`

### ISSUE THREAD

**Issue by skalish** [Datatamer/tamr-client#467]
We should follow through on a commitment to change the default branch name of the repo from the problematic name `master` to the Github-recommended name `main`.

**Comment by pcattori** [comment]
Github has [guidance for changing the default branch name](https://github.com/github/renaming).

Note that they claim to "make it seamless for existing repositories to rename their default branch. When you rename the branch, we’ll retarget your open PRs and draft releases, move your branch protection policies, and more - all automatically" by "later this year" (see [seamless move for existing repositories](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-))

**Comment by pcattori** [comment]
For instructions on updating your forks, see [Easily rename your Git default branch from master to main](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main)
