### ISSUE TITLE
Conflation between 'api_path', 'relative_id' / 'relativeId', and BaseResource ctor 'alias'

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/tamr-client#64]
# 💬 RFC

These terms are used nearly interchangeably:
- `Object.relative_id` (which reads `data["relativeId"]`)
- `Object.api_path`
- argument `alias` on `BaseResource.__init__`

## 🔦 Context

"relative ID" is an unfamiliar term.

I understand relative path, and api path. Those describe things that I'm familiar with.

If I had to vote for one, I'd request `api_path`, since it is tacked onto the end of the versioned API path.

Further confusing: sometimes `resource.api_path` is valid and populated, and sometimes different from `resource.relative_id`. This has to do with the path the resource was fetched from vs the canonical path that the resource lives at. For example, unified data sets.

```python3
>>> ds = project.unified_dataset()
>>> ds.api_path
'projects/3/unifiedDataset'
>>> ds.relative_id
'datasets/58'
```

How is this meant to be used?

## 💻 Examples

Before:
```python3
>>> client.datasets.by_relative_id('datasets/58')
<tamr_unify_client.models.dataset.resource.Dataset object at 0x7fe17cddee80>
```

After:
```python3
>>> client.datasets.by_api_path('datasets/58')
<tamr_unify_client.models.dataset.resource.Dataset object at 0x7fe17cddee80>
```

**Comment by pcattori** [comment]
Example:

`/api/versioned/v1/datasets/4` might be the canonical path for a dataset but if it happens to also be the unified dataset for project 1, then `/api/versioned/v1/projects/1/unifiedDataset` is an alias for that same resource.

Note that we wouldn't have to treat these cases specially if the API did the same things no matter which way you refer to the resource, but for our API if you do `/api/versioned/v1/datasets/4:refresh` it does a different thing than `/api/versioned/v1/projects/1/unifiedDataset:refresh`.

Keeping a reference to the (canonical) `relative_id` as well as the `alias` allows both behaviors to be possible.
