### ISSUE TITLE
Create new dataset

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/tamr-client#67]
# 💬 RFC

Trying to upload new data. I would prefer to create a new dataset, but the API doesn't support that. Instead, I need to use `Dataset.update_records`.

I would like to be able to create a new dataset.

## 🔦 Context

Concerns with updating into an existing dataset:
- Does not provide isolation of batches of data. With different datasets, I can map a given record to a particular load operation.
- Different datasets allow for partitioning, a common data management technique. Partitioning would allow for deletion of a single dataset and allow the dataset name to be an indicator of which data has already been uploaded (imagine that I have a system of uploading data daily, with a name based on the date).
- Records within a single dataset require unique `recordId` values, which requires additional management.
- Making a larger dataset causes later operations to be more costly. This further hurts the performance in the context of #66, for example.

It appears that the server's API does support the creation of new datasets, but this isn't provided in the python client. https://docs.tamr.com/reference#create-dataset

## 💁 Possible Solution

```
def create_dataset(unify, dataset_config):
    """
    Create a dataset in Unify
    
    :param unify: Unify Client
    :param dataset_config: Dataset Configuration
    :return: the created Dataset
    """
    from tamr_unify_client.models.dataset.resource import Dataset
    data = unify.post(unify.datasets.api_path, json=dataset_config).successful().json()
    return Dataset(unify, data, data["relativeId"])
```

**Comment by pcattori** [comment]
Related to #137

**Comment by pcattori** [comment]
@mollysacks this is asking for a convenience function that does:
1. (Empty) dataset creation
2. Set dataset schema
3. Upload all records to that dataset

**Comment by pcattori** [comment]
Design should be `Collection#create` e.g. `DatasetCollection.create`, not `Project#create_dataset` or  `Client#create_dataset`.

@mollysacks this is relevant for #150
