### ISSUE TITLE
Progress callback for synchronous actions

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/tamr-client#69]
# 💬 RFC

Many of the python client actions take a long while. While the default behavior of a synchronous action makes sense, it would be significantly improved if there were a simple callback that provided some indication of progress.

The progress is visible in the Unify UI, so I image that the data is available in the job operation data. It could be extracted and provided to a callback.

## 🔦 Context

Provide some information about how long something has taken and how far it is gotten, therefore offering some amount of insight into how much longer it might take.

## 💻 Examples

```python3
dataset = project.unifying_dataset()
def progress_callback(status, start_time, done, total):
    # ... print information or whatever.
dataset.refresh(progress_callback=progress_callback)
```

**Comment by pcattori** [comment]
UI uses an internal API that reports "steps completed" and "total steps" used to make the progress bar. The versioned API does not expose this information (at least not yet).

See [protobuf defintions for operations](https://github.com/Datatamer/javasrc/blob/develop/pubapi/proto/src/main/proto/v1.operation.proto) (versioned API analog to jobs) for data included in the JSON response.
