### ISSUE TITLE
Make some docs changes visible on the stable branch

### ISSUE THREAD

**Issue by pcattori** [Datatamer/tamr-client#77]
# 💬 RFC

Figure out a mechanism for pushing changes to the docs that should become immediately visible.

## 🔦 Context

If we don't want to change our code, but we do want to change the docs that describe that code, how do we do that? We want to change the [**stable** docs](https://tamr-unify-python-client.readthedocs.io/en/stable/), not the [**latest** docs](https://tamr-unify-python-client.readthedocs.io/en/latest/), but we don't want to necessitate a full release to do so.

## 💻 Examples

#58 adds refinements to the Contributor Guide, but those refinements are only visible on **latest** / `0.4.0-dev`. They should be visible on **stable** / `0.3.0` too.

---

We could add a commit to fix the docs both to `master` and to the most recent **stable** release branch. BUT readthedocs uses Github tags for building multiple versions of the docs, so we would need to re-tag after this commit got included? BUT the Github release is tied to the release tag... hmm 🤔

**Comment by Lordluen** [comment]
Would it make more sense to have a link in the stable docs to point to the latest docs? That way if someone wants to see what the current changes in the dev branch are, they could just jump to that via a quick link?

**Comment by pcattori** [comment]
Goal: `stable` docs should be what users look at. If we need to make docs modifications that don't reflect code changes, but instead reflect doc fixes/clarifications, those should land on `stable` (as well as `latest`).

The key point is that some doc changes (1) reflect new changes in the code made in the `-dev` version / `master` branch, while other doc changes (2) reflect doc fixes/clarifications for existing, unchanged code.

It would be great if (1) landed on `latest` and (2) landed *both* on `latest` and `stable`. The issue is that (according to readthedocs) `stable` is just the most recent Github tag. But tags are commit-based, not branch-based. So if we tag a commit as release `0.3.0` but then we want to make doc changes that should be included in `0.3.0`, we'd have to retag...

Tags are doing 2 things for us: (1) informing readthedocs what versions of the docs it should build and (2) tracking Github releases. (1) is tracking doc changes and (2) is tracking code changes.

---

Possible solutions:
a. Make readthedocs branch-aware instead of tag-aware
  - Figure out how to get branches named `release-<version>` to show up in readthedocs as just `<version>`
b. Add doc changes to the tip of the most recent release branch and retag the tip to be the release
  - How can we ensure we never accidentally retag with code changes? Don't want the code published on PyPI to deviate from the code marked as release on Github
c. Don't bother with this and instead just make doc changes on `latest`.
  - Users have to wait until the next release to see any doc changes that affect their version...
  - Add a link to `latest` from `stable` as suggested by @Lordluen

**Comment by pcattori** [comment]
`git` and Github support semver-formatted branches, and RTD supports branch-based docs. We should switch!

**Comment by nbateshaus** [comment]
A doc fix is still a fix; if the docs of 0.3.0 are improved, we should tag and release 0.3.1 with the doc changes.
This will include the changes for readthedocs, and also ensure the latest distribution has the doc fixes.
I'm not sure how this interacts with readthedocs's way of computing `stable`.
