### ISSUE TITLE
Proposal for extensibility

### ISSUE THREAD

**Issue by DerrickRice** [Datatamer/tamr-client#84]
# 💬 RFC

A proposal for cases where an end user wants to use this library, but add additional functionality without the difficulty of monkey-patching or of permanently modifying the library (even within a single Python runtime).

My proposal is to add a (barely-documented) class mapping argument to the `Client` which is used whenever a library class is invoked (i.e. a method is called on it, including it's constructor).

See https://github.com/DerrickRice/unify-client-python/commit/a6b644c8efcbdc2cf6344603fdff732433e530d4

## 💻 Examples

```Python3
def example():
    class_mapping = {ProjectCollection: MyProjectCollection}

    client = Client(
        UsernamePasswordAuth("username", "password"), class_mapping=class_mapping
    )

    assert isinstance(client.projects, MyProjectCollection)
```

**Comment by pcattori** [comment]
@yizhiyintamr , @alex-batchelor and I discussed this offline.

Extensions will be privately hosted in [Datatamer/tamr-client-extensions](https://github.com/Datatamer/tamr-client-extensions).
