### ISSUE TITLE
Create op helper structure for API calls outside of the versioned API

### ISSUE THREAD

**Issue by mrazo-tamr** [Datatamer/tamr-client#87]
Currently if we call a non-versioned or husk API, we cannot use the Operation status structure to check success or poll the operation status.

It would be great to have the Operation class generalized a bit so it can be used for custom API calls.

**Comment by juliamcclellan** [comment]
@mrazo-tamr Do the endpoints you're using have the operation information in their response body?

**Comment by pcattori** [comment]
All non-versioned API bindings/helpers etc.. should live in [tamr-client-extensions](https://github.com/Datatamer/tamr-client-extensions), not here.
